services:
  jdownloader:
    build:
      context: ./tests/docker
    ports:
      - 5800:5800
      - 3128:3128
    healthcheck:
      test: curl --fail http://localhost:3128/device/ping || exit 1
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 5s
