name: Run tests

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: false

      - name: Install dependencies
        run: |
          uv sync --all-extras

      - name: Smoke test
        run: |
          uv run python -c "from pyjd.jd_device import JDDevice"

      - name: Start JDownloader
        timeout-minutes: 5
        run: ./tests/docker/start_jdownloader.sh

      - name: Run tests
        timeout-minutes: 5
        run: uv run pytest -v --cov
