name: Run tests

on:
  push:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v0.11.18
        with:
          enable-cache: false

      - name: Install dependencies
        run: |
          uv sync --all-extras

      - name: Start JDownloader
        timeout-minutes: 5
        run: |
          docker compose up -d jdownloader
          until curl --fail --silent --show-error http://localhost:3128/device/ping; do
            sleep 30
          done

      - name: Run tests
        timeout-minutes: 5
        run: uv run pytest -v --cov
